/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  ListRunsQueryResponse,
  ListRunsQueryParams,
  ListRuns422,
} from '../../types/ListRuns.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';

export const listRunsSuspenseQueryKey = (params?: ListRunsQueryParams) =>
  [{ url: '/v1/runs/' }, ...(params ? [params] : [])] as const;

export type ListRunsSuspenseQueryKey = ReturnType<
  typeof listRunsSuspenseQueryKey
>;

/**
 * @description List all runs.
 * @summary List Runs
 * {@link /v1/runs/}
 */
export async function listRunsSuspense(
  params?: ListRunsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    ListRunsQueryResponse,
    ResponseErrorConfig<ListRuns422>,
    unknown
  >({ method: 'GET', url: `/v1/runs/`, params, ...requestConfig });
  return res;
}

export function listRunsSuspenseQueryOptions(
  params?: ListRunsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = listRunsSuspenseQueryKey(params);
  return queryOptions<
    ResponseConfig<ListRunsQueryResponse>,
    ResponseErrorConfig<ListRuns422>,
    ResponseConfig<ListRunsQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listRunsSuspense(params, config);
    },
  });
}

/**
 * @description List all runs.
 * @summary List Runs
 * {@link /v1/runs/}
 */
export function useListRunsSuspense<
  TData = ResponseConfig<ListRunsQueryResponse>,
  TQueryData = ResponseConfig<ListRunsQueryResponse>,
  TQueryKey extends QueryKey = ListRunsSuspenseQueryKey
>(
  params?: ListRunsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ResponseConfig<ListRunsQueryResponse>,
        ResponseErrorConfig<ListRuns422>,
        TData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? listRunsSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...(listRunsSuspenseQueryOptions(
        params,
        config
      ) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ListRuns422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
