/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  RetrieveRunUsageQueryResponse,
  RetrieveRunUsagePathParams,
  RetrieveRunUsage422,
} from '../../types/RetrieveRunUsage.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';

export const retrieveRunUsageSuspenseQueryKey = (
  run_id: RetrieveRunUsagePathParams['run_id']
) => [{ url: '/v1/runs/:run_id/usage', params: { run_id: run_id } }] as const;

export type RetrieveRunUsageSuspenseQueryKey = ReturnType<
  typeof retrieveRunUsageSuspenseQueryKey
>;

/**
 * @description Get usage statistics for a run.
 * @summary Retrieve Run Usage
 * {@link /v1/runs/:run_id/usage}
 */
export async function retrieveRunUsageSuspense(
  run_id: RetrieveRunUsagePathParams['run_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    RetrieveRunUsageQueryResponse,
    ResponseErrorConfig<RetrieveRunUsage422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/runs/${run_id}/usage`,
    ...requestConfig,
  });
  return res;
}

export function retrieveRunUsageSuspenseQueryOptions(
  run_id: RetrieveRunUsagePathParams['run_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = retrieveRunUsageSuspenseQueryKey(run_id);
  return queryOptions<
    ResponseConfig<RetrieveRunUsageQueryResponse>,
    ResponseErrorConfig<RetrieveRunUsage422>,
    ResponseConfig<RetrieveRunUsageQueryResponse>,
    typeof queryKey
  >({
    enabled: !!run_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return retrieveRunUsageSuspense(run_id, config);
    },
  });
}

/**
 * @description Get usage statistics for a run.
 * @summary Retrieve Run Usage
 * {@link /v1/runs/:run_id/usage}
 */
export function useRetrieveRunUsageSuspense<
  TData = ResponseConfig<RetrieveRunUsageQueryResponse>,
  TQueryData = ResponseConfig<RetrieveRunUsageQueryResponse>,
  TQueryKey extends QueryKey = RetrieveRunUsageSuspenseQueryKey
>(
  run_id: RetrieveRunUsagePathParams['run_id'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ResponseConfig<RetrieveRunUsageQueryResponse>,
        ResponseErrorConfig<RetrieveRunUsage422>,
        TData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? retrieveRunUsageSuspenseQueryKey(run_id);

  const query = useSuspenseQuery(
    {
      ...(retrieveRunUsageSuspenseQueryOptions(
        run_id,
        config
      ) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<RetrieveRunUsage422>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
