/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  ListAgentsQueryResponse,
  ListAgentsQueryParams,
  ListAgents422,
} from '../../types/ListAgents.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const listAgentsQueryKey = (params?: ListAgentsQueryParams) =>
  [{ url: '/v1/agents/' }, ...(params ? [params] : [])] as const;

export type ListAgentsQueryKey = ReturnType<typeof listAgentsQueryKey>;

/**
 * @description List all agents associated with a given user.This endpoint retrieves a list of all agents and their configurationsassociated with the specified user ID.
 * @summary List Agents
 * {@link /v1/agents/}
 */
export async function listAgents(
  params?: ListAgentsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    ListAgentsQueryResponse,
    ResponseErrorConfig<ListAgents422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/agents/`,
    params,
    ...requestConfig,
  });
  return res;
}

export function listAgentsQueryOptions(
  params?: ListAgentsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = listAgentsQueryKey(params);
  return queryOptions<
    ResponseConfig<ListAgentsQueryResponse>,
    ResponseErrorConfig<ListAgents422>,
    ResponseConfig<ListAgentsQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listAgents(params, config);
    },
  });
}

/**
 * @description List all agents associated with a given user.This endpoint retrieves a list of all agents and their configurationsassociated with the specified user ID.
 * @summary List Agents
 * {@link /v1/agents/}
 */
export function useListAgents<
  TData = ResponseConfig<ListAgentsQueryResponse>,
  TQueryData = ResponseConfig<ListAgentsQueryResponse>,
  TQueryKey extends QueryKey = ListAgentsQueryKey
>(
  params?: ListAgentsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        ResponseConfig<ListAgentsQueryResponse>,
        ResponseErrorConfig<ListAgents422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? listAgentsQueryKey(params);

  const query = useQuery(
    {
      ...(listAgentsQueryOptions(
        params,
        config
      ) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<ListAgents422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
