/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  ListAgentToolsQueryResponse,
  ListAgentToolsPathParams,
  ListAgentTools422,
} from '../../types/ListAgentTools.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';

export const listAgentToolsSuspenseQueryKey = (
  agent_id: ListAgentToolsPathParams['agent_id']
) =>
  [
    { url: '/v1/agents/:agent_id/tools', params: { agent_id: agent_id } },
  ] as const;

export type ListAgentToolsSuspenseQueryKey = ReturnType<
  typeof listAgentToolsSuspenseQueryKey
>;

/**
 * @description Get tools from an existing agent
 * @summary List Agent Tools
 * {@link /v1/agents/:agent_id/tools}
 */
export async function listAgentToolsSuspense(
  agent_id: ListAgentToolsPathParams['agent_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    ListAgentToolsQueryResponse,
    ResponseErrorConfig<ListAgentTools422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/agents/${agent_id}/tools`,
    ...requestConfig,
  });
  return res;
}

export function listAgentToolsSuspenseQueryOptions(
  agent_id: ListAgentToolsPathParams['agent_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = listAgentToolsSuspenseQueryKey(agent_id);
  return queryOptions<
    ResponseConfig<ListAgentToolsQueryResponse>,
    ResponseErrorConfig<ListAgentTools422>,
    ResponseConfig<ListAgentToolsQueryResponse>,
    typeof queryKey
  >({
    enabled: !!agent_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listAgentToolsSuspense(agent_id, config);
    },
  });
}

/**
 * @description Get tools from an existing agent
 * @summary List Agent Tools
 * {@link /v1/agents/:agent_id/tools}
 */
export function useListAgentToolsSuspense<
  TData = ResponseConfig<ListAgentToolsQueryResponse>,
  TQueryData = ResponseConfig<ListAgentToolsQueryResponse>,
  TQueryKey extends QueryKey = ListAgentToolsSuspenseQueryKey
>(
  agent_id: ListAgentToolsPathParams['agent_id'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ResponseConfig<ListAgentToolsQueryResponse>,
        ResponseErrorConfig<ListAgentTools422>,
        TData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? listAgentToolsSuspenseQueryKey(agent_id);

  const query = useSuspenseQuery(
    {
      ...(listAgentToolsSuspenseQueryOptions(
        agent_id,
        config
      ) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ListAgentTools422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
