/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  ListMessagesQueryResponse,
  ListMessagesPathParams,
  ListMessagesQueryParams,
  ListMessages422,
} from '../../types/ListMessages.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  InfiniteQueryObserverOptions,
  UseInfiniteQueryResult,
} from '@tanstack/react-query';
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query';

export const listMessagesInfiniteQueryKey = (
  agent_id: ListMessagesPathParams['agent_id'],
  params?: ListMessagesQueryParams
) =>
  [
    { url: '/v1/agents/:agent_id/messages', params: { agent_id: agent_id } },
    ...(params ? [params] : []),
  ] as const;

export type ListMessagesInfiniteQueryKey = ReturnType<
  typeof listMessagesInfiniteQueryKey
>;

/**
 * @description Retrieve message history for an agent.
 * @summary List Messages
 * {@link /v1/agents/:agent_id/messages}
 */
export async function listMessagesInfinite(
  agent_id: ListMessagesPathParams['agent_id'],
  params?: ListMessagesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    ListMessagesQueryResponse,
    ResponseErrorConfig<ListMessages422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/agents/${agent_id}/messages`,
    params,
    ...requestConfig,
  });
  return res;
}

export function listMessagesInfiniteQueryOptions(
  agent_id: ListMessagesPathParams['agent_id'],
  params?: ListMessagesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = listMessagesInfiniteQueryKey(agent_id, params);
  return infiniteQueryOptions<
    ResponseConfig<ListMessagesQueryResponse>,
    ResponseErrorConfig<ListMessages422>,
    ResponseConfig<ListMessagesQueryResponse>,
    typeof queryKey,
    number
  >({
    enabled: !!agent_id,
    queryKey,
    queryFn: async ({ signal, pageParam }) => {
      config.signal = signal;

      if (params) {
        params['next_page'] =
          pageParam as unknown as ListMessagesQueryParams['next_page'];
      }
      return listMessagesInfinite(agent_id, params, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  });
}

/**
 * @description Retrieve message history for an agent.
 * @summary List Messages
 * {@link /v1/agents/:agent_id/messages}
 */
export function useListMessagesInfinite<
  TData = InfiniteData<ResponseConfig<ListMessagesQueryResponse>>,
  TQueryData = ResponseConfig<ListMessagesQueryResponse>,
  TQueryKey extends QueryKey = ListMessagesInfiniteQueryKey
>(
  agent_id: ListMessagesPathParams['agent_id'],
  params?: ListMessagesQueryParams,
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<ListMessagesQueryResponse>,
        ResponseErrorConfig<ListMessages422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? listMessagesInfiniteQueryKey(agent_id, params);

  const query = useInfiniteQuery(
    {
      ...(listMessagesInfiniteQueryOptions(
        agent_id,
        params,
        config
      ) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<
        InfiniteQueryObserverOptions,
        'queryKey'
      >),
    },
    queryClient
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<ListMessages422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
