/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  RetrieveAgentQueryResponse,
  RetrieveAgentPathParams,
  RetrieveAgent422,
} from '../../types/RetrieveAgent.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const retrieveAgentQueryKey = (
  agent_id: RetrieveAgentPathParams['agent_id']
) => [{ url: '/v1/agents/:agent_id', params: { agent_id: agent_id } }] as const;

export type RetrieveAgentQueryKey = ReturnType<typeof retrieveAgentQueryKey>;

/**
 * @description Get the state of the agent.
 * @summary Retrieve Agent
 * {@link /v1/agents/:agent_id}
 */
export async function retrieveAgent(
  agent_id: RetrieveAgentPathParams['agent_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    RetrieveAgentQueryResponse,
    ResponseErrorConfig<RetrieveAgent422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/agents/${agent_id}`,
    ...requestConfig,
  });
  return res;
}

export function retrieveAgentQueryOptions(
  agent_id: RetrieveAgentPathParams['agent_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = retrieveAgentQueryKey(agent_id);
  return queryOptions<
    ResponseConfig<RetrieveAgentQueryResponse>,
    ResponseErrorConfig<RetrieveAgent422>,
    ResponseConfig<RetrieveAgentQueryResponse>,
    typeof queryKey
  >({
    enabled: !!agent_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return retrieveAgent(agent_id, config);
    },
  });
}

/**
 * @description Get the state of the agent.
 * @summary Retrieve Agent
 * {@link /v1/agents/:agent_id}
 */
export function useRetrieveAgent<
  TData = ResponseConfig<RetrieveAgentQueryResponse>,
  TQueryData = ResponseConfig<RetrieveAgentQueryResponse>,
  TQueryKey extends QueryKey = RetrieveAgentQueryKey
>(
  agent_id: RetrieveAgentPathParams['agent_id'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        ResponseConfig<RetrieveAgentQueryResponse>,
        ResponseErrorConfig<RetrieveAgent422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? retrieveAgentQueryKey(agent_id);

  const query = useQuery(
    {
      ...(retrieveAgentQueryOptions(
        agent_id,
        config
      ) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<RetrieveAgent422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
