/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  RetrieveAgentMemoryQueryResponse,
  RetrieveAgentMemoryPathParams,
  RetrieveAgentMemory422,
} from '../../types/RetrieveAgentMemory.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  InfiniteQueryObserverOptions,
  UseInfiniteQueryResult,
} from '@tanstack/react-query';
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query';

export const retrieveAgentMemoryInfiniteQueryKey = (
  agent_id: RetrieveAgentMemoryPathParams['agent_id']
) =>
  [
    { url: '/v1/agents/:agent_id/core-memory', params: { agent_id: agent_id } },
  ] as const;

export type RetrieveAgentMemoryInfiniteQueryKey = ReturnType<
  typeof retrieveAgentMemoryInfiniteQueryKey
>;

/**
 * @description Retrieve the memory state of a specific agent.This endpoint fetches the current memory state of the agent identified by the user ID and agent ID.
 * @summary Retrieve Agent Memory
 * {@link /v1/agents/:agent_id/core-memory}
 */
export async function retrieveAgentMemoryInfinite(
  agent_id: RetrieveAgentMemoryPathParams['agent_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    RetrieveAgentMemoryQueryResponse,
    ResponseErrorConfig<RetrieveAgentMemory422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/agents/${agent_id}/core-memory`,
    ...requestConfig,
  });
  return res;
}

export function retrieveAgentMemoryInfiniteQueryOptions(
  agent_id: RetrieveAgentMemoryPathParams['agent_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = retrieveAgentMemoryInfiniteQueryKey(agent_id);
  return infiniteQueryOptions<
    ResponseConfig<RetrieveAgentMemoryQueryResponse>,
    ResponseErrorConfig<RetrieveAgentMemory422>,
    ResponseConfig<RetrieveAgentMemoryQueryResponse>,
    typeof queryKey
  >({
    enabled: !!agent_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return retrieveAgentMemoryInfinite(agent_id, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  });
}

/**
 * @description Retrieve the memory state of a specific agent.This endpoint fetches the current memory state of the agent identified by the user ID and agent ID.
 * @summary Retrieve Agent Memory
 * {@link /v1/agents/:agent_id/core-memory}
 */
export function useRetrieveAgentMemoryInfinite<
  TData = InfiniteData<ResponseConfig<RetrieveAgentMemoryQueryResponse>>,
  TQueryData = ResponseConfig<RetrieveAgentMemoryQueryResponse>,
  TQueryKey extends QueryKey = RetrieveAgentMemoryInfiniteQueryKey
>(
  agent_id: RetrieveAgentMemoryPathParams['agent_id'],
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<RetrieveAgentMemoryQueryResponse>,
        ResponseErrorConfig<RetrieveAgentMemory422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? retrieveAgentMemoryInfiniteQueryKey(agent_id);

  const query = useInfiniteQuery(
    {
      ...(retrieveAgentMemoryInfiniteQueryOptions(
        agent_id,
        config
      ) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<
        InfiniteQueryObserverOptions,
        'queryKey'
      >),
    },
    queryClient
  ) as UseInfiniteQueryResult<
    TData,
    ResponseErrorConfig<RetrieveAgentMemory422>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
