/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ClientSideAccessTokensDeleteClientSideAccessTokenPathParams = {
  /**
   * @description The access token to delete
   * @type string
   */
  token: string;
};

/**
 * @description 204
 */
export type ClientSideAccessTokensDeleteClientSideAccessToken204 = any;

/**
 * @description 400
 */
export type ClientSideAccessTokensDeleteClientSideAccessToken400 = {
  /**
   * @type string
   */
  message: string;
};

/**
 * @description Body
 */
export type ClientSideAccessTokensDeleteClientSideAccessTokenMutationRequest =
  any;

export type ClientSideAccessTokensDeleteClientSideAccessTokenMutationResponse =
  ClientSideAccessTokensDeleteClientSideAccessToken204;

export type ClientSideAccessTokensDeleteClientSideAccessTokenMutation = {
  Response: ClientSideAccessTokensDeleteClientSideAccessToken204;
  Request: ClientSideAccessTokensDeleteClientSideAccessTokenMutationRequest;
  PathParams: ClientSideAccessTokensDeleteClientSideAccessTokenPathParams;
  Errors: ClientSideAccessTokensDeleteClientSideAccessToken400;
};
