/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AgentsMigrateAgentPathParams = {
  /**
   * @type string
   */
  agent_id: string
}

export const agentsMigrateAgent200SuccessEnum = {
  true: true,
} as const

export type AgentsMigrateAgent200SuccessEnum = (typeof agentsMigrateAgent200SuccessEnum)[keyof typeof agentsMigrateAgent200SuccessEnum]

/**
 * @description 200
 */
export type AgentsMigrateAgent200 = {
  /**
   * @type boolean
   */
  success: AgentsMigrateAgent200SuccessEnum
}

export const agentsMigrateAgent404MessageEnum = {
  'Agent provided is a template or not found, you can only migrate deployed agents':
    'Agent provided is a template or not found, you can only migrate deployed agents',
  'Template version provided does not exist': 'Template version provided does not exist',
} as const

export type AgentsMigrateAgent404MessageEnum = (typeof agentsMigrateAgent404MessageEnum)[keyof typeof agentsMigrateAgent404MessageEnum]

/**
 * @description 404
 */
export type AgentsMigrateAgent404 = {
  /**
   * @type string
   */
  message: AgentsMigrateAgent404MessageEnum
}

export const agentsMigrateAgent409MessageEnum = {
  'You can only migrate agents to a new versioned agent template that belongs to the same project':
    'You can only migrate agents to a new versioned agent template that belongs to the same project',
} as const

export type AgentsMigrateAgent409MessageEnum = (typeof agentsMigrateAgent409MessageEnum)[keyof typeof agentsMigrateAgent409MessageEnum]

/**
 * @description 409
 */
export type AgentsMigrateAgent409 = {
  /**
   * @type string
   */
  message: AgentsMigrateAgent409MessageEnum
}

export const agentsMigrateAgent500MessageEnum = {
  'Migration failed': 'Migration failed',
} as const

export type AgentsMigrateAgent500MessageEnum = (typeof agentsMigrateAgent500MessageEnum)[keyof typeof agentsMigrateAgent500MessageEnum]

/**
 * @description 500
 */
export type AgentsMigrateAgent500 = {
  /**
   * @type string
   */
  message: AgentsMigrateAgent500MessageEnum
}

/**
 * @description Body
 */
export type AgentsMigrateAgentMutationRequest = {
  /**
   * @type string
   */
  to_template: string
  /**
   * @description If you chose to not preserve core memories, you should provide the new variables for the core memories
   * @type object | undefined
   */
  variables?: {
    [key: string]: string
  }
  /**
   * @type boolean
   */
  preserve_core_memories: boolean
}

export type AgentsMigrateAgentMutationResponse = AgentsMigrateAgent200

export type AgentsMigrateAgentMutation = {
  Response: AgentsMigrateAgent200
  Request: AgentsMigrateAgentMutationRequest
  PathParams: AgentsMigrateAgentPathParams
  Errors: AgentsMigrateAgent404 | AgentsMigrateAgent409 | AgentsMigrateAgent500
}