/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  RetrieveBlockQueryResponse,
  RetrieveBlockPathParams,
  RetrieveBlock422,
} from '../../types/RetrieveBlock.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';

export const retrieveBlockSuspenseQueryKey = (
  block_id: RetrieveBlockPathParams['block_id']
) => [{ url: '/v1/blocks/:block_id', params: { block_id: block_id } }] as const;

export type RetrieveBlockSuspenseQueryKey = ReturnType<
  typeof retrieveBlockSuspenseQueryKey
>;

/**
 * @summary Retrieve Block
 * {@link /v1/blocks/:block_id}
 */
export async function retrieveBlockSuspense(
  block_id: RetrieveBlockPathParams['block_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    RetrieveBlockQueryResponse,
    ResponseErrorConfig<RetrieveBlock422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/blocks/${block_id}`,
    ...requestConfig,
  });
  return res;
}

export function retrieveBlockSuspenseQueryOptions(
  block_id: RetrieveBlockPathParams['block_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = retrieveBlockSuspenseQueryKey(block_id);
  return queryOptions<
    ResponseConfig<RetrieveBlockQueryResponse>,
    ResponseErrorConfig<RetrieveBlock422>,
    ResponseConfig<RetrieveBlockQueryResponse>,
    typeof queryKey
  >({
    enabled: !!block_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return retrieveBlockSuspense(block_id, config);
    },
  });
}

/**
 * @summary Retrieve Block
 * {@link /v1/blocks/:block_id}
 */
export function useRetrieveBlockSuspense<
  TData = ResponseConfig<RetrieveBlockQueryResponse>,
  TQueryData = ResponseConfig<RetrieveBlockQueryResponse>,
  TQueryKey extends QueryKey = RetrieveBlockSuspenseQueryKey
>(
  block_id: RetrieveBlockPathParams['block_id'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ResponseConfig<RetrieveBlockQueryResponse>,
        ResponseErrorConfig<RetrieveBlock422>,
        TData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? retrieveBlockSuspenseQueryKey(block_id);

  const query = useSuspenseQuery(
    {
      ...(retrieveBlockSuspenseQueryOptions(
        block_id,
        config
      ) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<RetrieveBlock422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
