/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Action response data model.
 */
export type ActionResponseModel = {
  /**
   * @type object
   */
  properties: {
    [key: string]: any;
  };
  /**
   * @type string
   */
  title: string;
  /**
   * @type string
   */
  type: string;
  required?: string[] | null;
  examples?: any[] | null;
};
