/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AgentEnvironmentVariable } from './AgentEnvironmentVariable.ts'
import type { AgentType } from './AgentType.ts'
import type { ChildToolRule } from './ChildToolRule.ts'
import type { ConditionalToolRule } from './ConditionalToolRule.ts'
import type { ContinueToolRule } from './ContinueToolRule.ts'
import type { EmbeddingConfig } from './EmbeddingConfig.ts'
import type { Group } from './Group.ts'
import type { InitToolRule } from './InitToolRule.ts'
import type { LLMConfig } from './LLMConfig.ts'
import type { MaxCountPerStepToolRule } from './MaxCountPerStepToolRule.ts'
import type { Memory } from './Memory.ts'
import type { ParentToolRule } from './ParentToolRule.ts'
import type { Source } from './Source.ts'
import type { TerminalToolRule } from './TerminalToolRule.ts'
import type { Tool } from './Tool.ts'

/**
 * @description Representation of an agent\'s state. This is the state of the agent at a given time, and is persisted in the DB backend. The state has all the information needed to recreate a persisted agent.\n\nParameters:\n    id (str): The unique identifier of the agent.\n    name (str): The name of the agent (must be unique to the user).\n    created_at (datetime): The datetime the agent was created.\n    message_ids (List[str]): The ids of the messages in the agent\'s in-context memory.\n    memory (Memory): The in-context memory of the agent.\n    tools (List[str]): The tools used by the agent. This includes any memory editing functions specified in `memory`.\n    system (str): The system prompt used by the agent.\n    llm_config (LLMConfig): The LLM configuration used by the agent.\n    embedding_config (EmbeddingConfig): The embedding configuration used by the agent.
 */
export type AgentState = {
  /**
   * @description The id of the user that made this object.
   */
  created_by_id?: string | null
  /**
   * @description The id of the user that made this object.
   */
  last_updated_by_id?: string | null
  /**
   * @description The timestamp when the object was created.
   */
  created_at?: string | null
  /**
   * @description The timestamp when the object was last updated.
   */
  updated_at?: string | null
  /**
   * @description The id of the agent. Assigned by the database.
   * @type string
   */
  id: string
  /**
   * @description The name of the agent.
   * @type string
   */
  name: string
  /**
   * @description The list of tool rules.
   */
  tool_rules?: (ChildToolRule | InitToolRule | TerminalToolRule | ConditionalToolRule | ContinueToolRule | MaxCountPerStepToolRule | ParentToolRule)[] | null
  /**
   * @description The ids of the messages in the agent\'s in-context memory.
   */
  message_ids?: string[] | null
  /**
   * @description The system prompt used by the agent.
   * @type string
   */
  system: string
  /**
   * @type string
   */
  agent_type: AgentType
  /**
   * @type object
   */
  llm_config: LLMConfig
  /**
   * @type object
   */
  embedding_config: EmbeddingConfig
  /**
   * @description The description of the agent.
   */
  description?: string | null
  /**
   * @description The metadata of the agent.
   */
  metadata?: {
    [key: string]: any
  } | null
  /**
   * @type object
   */
  memory: Memory
  /**
   * @description The tools used by the agent.
   * @type array
   */
  tools: Tool[]
  /**
   * @description The sources used by the agent.
   * @type array
   */
  sources: Source[]
  /**
   * @description The tags associated with the agent.
   * @type array
   */
  tags: string[]
  /**
   * @description The environment variables for tool execution specific to this agent.
   * @type array | undefined
   */
  tool_exec_environment_variables?: AgentEnvironmentVariable[]
  /**
   * @description The id of the project the agent belongs to.
   */
  project_id?: string | null
  /**
   * @description The id of the template the agent belongs to.
   */
  template_id?: string | null
  /**
   * @description The base template id of the agent.
   */
  base_template_id?: string | null
  /**
   * @description The ids of the identities associated with this agent.
   * @type array | undefined
   */
  identity_ids?: string[]
  /**
   * @description If set to True, the agent will not remember previous messages (though the agent will still retain state via core memory blocks and archival/recall memory). Not recommended unless you have an advanced use case.
   * @default false
   * @type boolean | undefined
   */
  message_buffer_autoclear?: boolean
  /**
   * @description If set to True, memory management will move to a background agent thread.
   */
  enable_sleeptime?: boolean | null
  /**
   * @description The multi-agent group that this agent manages
   */
  multi_agent_group?: Group | null
}