/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AuthResponse = {
  /**
   * @description UUID of the user
   * @type string, uuid
   */
  uuid: string
  /**
   * @description Whether the user is an admin
   */
  is_admin?: boolean | null
}