/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description A Block represents a reserved section of the LLM\'s context window which is editable. `Block` objects contained in the `Memory` object, which is able to edit the Block values.\n\nParameters:\n    label (str): The label of the block (e.g. \'human\', \'persona\'). This defines a category for the block.\n    value (str): The value of the block. This is the string that is represented in the context window.\n    limit (int): The character limit of the block.\n    is_template (bool): Whether the block is a template (e.g. saved human/persona options). Non-template blocks are not stored in the database and are ephemeral, while templated blocks are stored in the database.\n    label (str): The label of the block (e.g. \'human\', \'persona\'). This defines a category for the block.\n    template_name (str): The name of the block template (if it is a template).\n    description (str): Description of the block.\n    metadata (Dict): Metadata of the block.\n    user_id (str): The unique identifier of the user associated with the block.
 */
export type Block = {
  /**
   * @description Value of the block.
   * @type string
   */
  value: string;
  /**
   * @description Character limit of the block.
   * @default 5000
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @description Name of the block if it is a template.
   */
  name?: string | null;
  /**
   * @description Whether the block is a template (e.g. saved human/persona options).
   * @default false
   * @type boolean | undefined
   */
  is_template?: boolean;
  /**
   * @description Label of the block (e.g. \'human\', \'persona\') in the context window.
   */
  label?: string | null;
  /**
   * @description Description of the block.
   */
  description?: string | null;
  /**
   * @description Metadata of the block.
   * @default [object Object]
   */
  metadata?: {
    [key: string]: any;
  } | null;
  /**
   * @description The human-friendly ID of the Block
   * @pattern ^block-[a-fA-F0-9]{8}
   * @type string | undefined
   */
  id?: string;
  /**
   * @description The id of the user that made this Block.
   */
  created_by_id?: string | null;
  /**
   * @description The id of the user that last updated this Block.
   */
  last_updated_by_id?: string | null;
};
