/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction } from './OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction.ts'

export type ChatCompletionNamedToolChoiceParam = {
  /**
   * @type object
   */
  function: OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction
  /**
   * @type string
   */
  type: 'function'
}