/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ChatCompletionContentPartTextParam } from './ChatCompletionContentPartTextParam.ts'

export type ChatCompletionDeveloperMessageParam = {
  content: string | ChatCompletionContentPartTextParam[]
  /**
   * @type string
   */
  role: 'developer'
  /**
   * @type string | undefined
   */
  name?: string
}