/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ChatCompletionContentPartTextParam } from './ChatCompletionContentPartTextParam.ts';

export type ChatCompletionPredictionContentParam = {
  content: string | ChatCompletionContentPartTextParam[];
  /**
   * @type string
   */
  type: 'content';
};
