/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ChatCompletionContentPartTextParam = {
  /**
   * @type string
   */
  text: string
  /**
   * @type string
   */
  type: 'text'
}