/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ImageURL } from './ImageURL.ts'

export type ChatCompletionContentPartImageParam = {
  /**
   * @type object
   */
  image_url: ImageURL
  /**
   * @type string
   */
  type: 'image_url'
}