/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ChatCompletionFunctionMessageParam = {
  content: string | null
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  role: 'function'
}