/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ChatCompletionContentPartRefusalParam = {
  /**
   * @type string
   */
  refusal: string;
  /**
   * @type string
   */
  type: 'refusal';
};
