/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ChatCompletionContentPartTextParam } from './ChatCompletionContentPartTextParam.ts'

export type ChatCompletionToolMessageParam = {
  content: string | ChatCompletionContentPartTextParam[]
  /**
   * @type string
   */
  role: 'tool'
  /**
   * @type string
   */
  tool_call_id: string
}