/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FunctionOutput } from './FunctionOutput.ts'

export type ChatCompletionMessageToolCall = {
  /**
   * @type string
   */
  id: string
  /**
   * @type object
   */
  function: FunctionOutput
  /**
   * @type string
   */
  type: 'function'
  [key: string]: any
}