/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FunctionTool } from './FunctionTool.ts';
import type { Message } from './Message.ts';

/**
 * @description Overview of the context window, including the number of messages and tokens.
 */
export type ContextWindowOverview = {
  /**
   * @description The maximum amount of tokens the context window can hold.
   * @type integer
   */
  context_window_size_max: number;
  /**
   * @description The current number of tokens in the context window.
   * @type integer
   */
  context_window_size_current: number;
  /**
   * @description The number of messages in the context window.
   * @type integer
   */
  num_messages: number;
  /**
   * @description The number of messages in the archival memory.
   * @type integer
   */
  num_archival_memory: number;
  /**
   * @description The number of messages in the recall memory.
   * @type integer
   */
  num_recall_memory: number;
  /**
   * @description The number of tokens in the external memory summary (archival + recall metadata).
   * @type integer
   */
  num_tokens_external_memory_summary: number;
  /**
   * @description The metadata summary of the external memory sources (archival + recall metadata).
   * @type string
   */
  external_memory_summary: string;
  /**
   * @description The number of tokens in the system prompt.
   * @type integer
   */
  num_tokens_system: number;
  /**
   * @description The content of the system prompt.
   * @type string
   */
  system_prompt: string;
  /**
   * @description The number of tokens in the core memory.
   * @type integer
   */
  num_tokens_core_memory: number;
  /**
   * @description The content of the core memory.
   * @type string
   */
  core_memory: string;
  /**
   * @description The number of tokens in the summary memory.
   * @type integer
   */
  num_tokens_summary_memory: number;
  /**
   * @description The content of the summary memory.
   */
  summary_memory?: string | null;
  /**
   * @description The number of tokens in the functions definitions.
   * @type integer
   */
  num_tokens_functions_definitions: number;
  /**
   * @description The content of the functions definitions.
   */
  functions_definitions: FunctionTool[] | null;
  /**
   * @description The number of tokens in the messages list.
   * @type integer
   */
  num_tokens_messages: number;
  /**
   * @description The messages in the context window.
   * @type array
   */
  messages: Message[];
};
