/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CoreMemoryBlockSchema = {
  /**
   * @type string
   */
  created_at: string;
  description: string | null;
  /**
   * @type boolean
   */
  is_template: boolean;
  /**
   * @type string
   */
  label: string;
  /**
   * @type integer
   */
  limit: number;
  metadata_?: {
    [key: string]: any;
  } | null;
  template_name: string | null;
  /**
   * @type string
   */
  updated_at: string;
  /**
   * @type string
   */
  value: string;
};
