/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from './HTTPValidationError.ts'
import type { Provider } from './Provider.ts'
import type { ProviderCreate } from './ProviderCreate.ts'

/**
 * @description Successful Response
 */
export type CreateProvider200 = Provider

/**
 * @description Validation Error
 */
export type CreateProvider422 = HTTPValidationError

export type CreateProviderMutationRequest = ProviderCreate

export type CreateProviderMutationResponse = CreateProvider200

export type CreateProviderMutation = {
  Response: CreateProvider200
  Request: CreateProviderMutationRequest
  Errors: CreateProvider422
}