/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateArchivalMemory = {
  /**
   * @description Text to write to archival memory.
   * @type string
   */
  text: string;
};
