/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type E2BSandboxConfig = {
  /**
   * @description Time limit for the sandbox (in seconds).
   * @default 300
   * @type integer | undefined
   */
  timeout?: number
  /**
   * @description The E2B template id (docker image).
   */
  template?: string | null
  /**
   * @description A list of pip packages to install on the E2B Sandbox
   */
  pip_requirements?: string[] | null
}