/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type FileFile = {
  /**
   * @type string | undefined
   */
  file_data?: string;
  /**
   * @type string | undefined
   */
  file_id?: string;
  /**
   * @type string | undefined
   */
  filename?: string;
};
