/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FileFile } from './FileFile.ts'

export type File = {
  /**
   * @type object
   */
  file: FileFile
  /**
   * @type string
   */
  type: 'file'
}