/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type FunctionOutput = {
  /**
   * @type string
   */
  arguments: string
  /**
   * @type string
   */
  name: string
  [key: string]: any
}