/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const identityPropertyTypeEnum = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  json: 'json',
} as const

export type IdentityPropertyTypeEnum = (typeof identityPropertyTypeEnum)[keyof typeof identityPropertyTypeEnum]

/**
 * @description Enum to represent the type of the identity property.
 */
export type IdentityPropertyType = IdentityPropertyTypeEnum