/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const identityTypeEnum = {
  org: 'org',
  user: 'user',
  other: 'other',
} as const;

export type IdentityTypeEnum =
  (typeof identityTypeEnum)[keyof typeof identityTypeEnum];

/**
 * @description Enum to represent the type of the identity.
 */
export type IdentityType = IdentityTypeEnum;
