/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const imageURLDetailEnum = {
  auto: 'auto',
  low: 'low',
  high: 'high',
} as const

export type ImageURLDetailEnum = (typeof imageURLDetailEnum)[keyof typeof imageURLDetailEnum]

export type ImageURL = {
  /**
   * @type string
   */
  url: string
  /**
   * @type string | undefined
   */
  detail?: ImageURLDetailEnum
}