/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Represents the initial tool rule configuration.
 */
export type InitToolRule = {
  /**
   * @description The name of the tool. Must exist in the database for the user\'s organization.
   * @type string
   */
  tool_name: string;
  /**
   * @default "run_first"
   * @type string | undefined
   */
  type?: 'run_first';
};
