/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const jobTypeEnum = {
  job: 'job',
  run: 'run',
} as const;

export type JobTypeEnum = (typeof jobTypeEnum)[keyof typeof jobTypeEnum];

export type JobType = JobTypeEnum;
