/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TextContent } from './TextContent.ts'

export const lettaAssistantMessageContentUnionTypeEnum = {
  text: 'text',
} as const

export type LettaAssistantMessageContentUnionTypeEnum =
  (typeof lettaAssistantMessageContentUnionTypeEnum)[keyof typeof lettaAssistantMessageContentUnionTypeEnum]

export type LettaAssistantMessageContentUnion = TextContent & {
  type?: LettaAssistantMessageContentUnionTypeEnum
}