/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Message } from './Message.ts';

/**
 * @description Usage statistics for the agent interaction.\n\nAttributes:\n    completion_tokens (int): The number of tokens generated by the agent.\n    prompt_tokens (int): The number of tokens in the prompt.\n    total_tokens (int): The total number of tokens processed by the agent.\n    step_count (int): The number of steps taken by the agent.
 */
export type LettaUsageStatistics = {
  /**
   * @default "usage_statistics"
   * @type string | undefined
   */
  message_type?: 'usage_statistics';
  /**
   * @description The number of tokens generated by the agent.
   * @default 0
   * @type integer | undefined
   */
  completion_tokens?: number;
  /**
   * @description The number of tokens in the prompt.
   * @default 0
   * @type integer | undefined
   */
  prompt_tokens?: number;
  /**
   * @description The total number of tokens processed by the agent.
   * @default 0
   * @type integer | undefined
   */
  total_tokens?: number;
  /**
   * @description The number of steps taken by the agent.
   * @default 0
   * @type integer | undefined
   */
  step_count?: number;
  /**
   * @description The messages generated per step
   */
  steps_messages?: Message[][] | null;
  /**
   * @description The background task run IDs associated with the agent interaction
   */
  run_ids?: string[] | null;
};
