/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OmittedReasoningContent } from './OmittedReasoningContent.ts'
import type { ReasoningContent } from './ReasoningContent.ts'
import type { RedactedReasoningContent } from './RedactedReasoningContent.ts'
import type { TextContent } from './TextContent.ts'
import type { ToolCallContent } from './ToolCallContent.ts'
import type { ToolReturnContent } from './ToolReturnContent.ts'

export const lettaMessageContentUnionTypeEnum = {
  text: 'text',
  tool_call: 'tool_call',
  tool_return: 'tool_return',
  reasoning: 'reasoning',
  redacted_reasoning: 'redacted_reasoning',
  omitted_reasoning: 'omitted_reasoning',
} as const

export type LettaMessageContentUnionTypeEnum = (typeof lettaMessageContentUnionTypeEnum)[keyof typeof lettaMessageContentUnionTypeEnum]

export type LettaMessageContentUnion =
  | (TextContent & {
      type?: LettaMessageContentUnionTypeEnum
    })
  | (ToolCallContent & {
      type?: LettaMessageContentUnionTypeEnum
    })
  | (ToolReturnContent & {
      type?: LettaMessageContentUnionTypeEnum
    })
  | (ReasoningContent & {
      type?: LettaMessageContentUnionTypeEnum
    })
  | (RedactedReasoningContent & {
      type?: LettaMessageContentUnionTypeEnum
    })
  | (OmittedReasoningContent & {
      type?: LettaMessageContentUnionTypeEnum
    })