/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LettaMessageUnion } from './LettaMessageUnion.ts';
import type { LettaUsageStatistics } from './LettaUsageStatistics.ts';

/**
 * @description Response object from an agent interaction, consisting of the new messages generated by the agent and usage statistics.\nThe type of the returned messages can be either `Message` or `LettaMessage`, depending on what was specified in the request.\n\nAttributes:\n    messages (List[Union[Message, LettaMessage]]): The messages returned by the agent.\n    usage (LettaUsageStatistics): The usage statistics
 */
export type LettaResponse = {
  /**
   * @description The messages returned by the agent.
   * @type array
   */
  messages: LettaMessageUnion[];
  /**
   * @type object
   */
  usage: LettaUsageStatistics;
};
