/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Group } from './Group.ts'
import type { HTTPValidationError } from './HTTPValidationError.ts'
import type { ManagerType } from './ManagerType.ts'

export type ListGroupsQueryParams = {
  /**
   * @description Search groups by manager type
   */
  manager_type?: ManagerType | null
  /**
   * @description Cursor for pagination
   */
  before?: string | null
  /**
   * @description Cursor for pagination
   */
  after?: string | null
  /**
   * @description Limit for pagination
   */
  limit?: number | null
  /**
   * @description Search groups by project id
   */
  project_id?: string | null
}

/**
 * @description Successful Response
 */
export type ListGroups200 = Group[]

/**
 * @description Validation Error
 */
export type ListGroups422 = HTTPValidationError

export type ListGroupsQueryResponse = ListGroups200

export type ListGroupsQuery = {
  Response: ListGroups200
  QueryParams: ListGroupsQueryParams
  Errors: ListGroups422
}