/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from './HTTPValidationError.ts'
import type { Job } from './Job.ts'

/**
 * @description Successful Response
 */
export type ListActiveJobs200 = Job[]

/**
 * @description Validation Error
 */
export type ListActiveJobs422 = HTTPValidationError

export type ListActiveJobsQueryResponse = ListActiveJobs200

export type ListActiveJobsQuery = {
  Response: ListActiveJobs200
  Errors: ListActiveJobs422
}