/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from './HTTPValidationError.ts'
import type { Step } from './Step.ts'

export type ListStepsQueryParams = {
  /**
   * @description Return steps before this step ID
   */
  before?: string | null
  /**
   * @description Return steps after this step ID
   */
  after?: string | null
  /**
   * @description Maximum number of steps to return
   * @default 50
   */
  limit?: number | null
  /**
   * @description Sort order (asc or desc)
   * @default "desc"
   */
  order?: string | null
  /**
   * @description Return steps after this ISO datetime (e.g. \"2025-01-29T15:01:19-08:00\")
   */
  start_date?: string | null
  /**
   * @description Return steps before this ISO datetime (e.g. \"2025-01-29T15:01:19-08:00\")
   */
  end_date?: string | null
  /**
   * @description Filter by the name of the model used for the step
   */
  model?: string | null
  /**
   * @description Filter by the ID of the agent that performed the step
   */
  agent_id?: string | null
}

/**
 * @description Successful Response
 */
export type ListSteps200 = Step[]

/**
 * @description Validation Error
 */
export type ListSteps422 = HTTPValidationError

export type ListStepsQueryResponse = ListSteps200

export type ListStepsQuery = {
  Response: ListSteps200
  QueryParams: ListStepsQueryParams
  Errors: ListSteps422
}