/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const managerTypeEnum = {
  round_robin: 'round_robin',
  supervisor: 'supervisor',
  dynamic: 'dynamic',
  sleeptime: 'sleeptime',
  swarm: 'swarm',
} as const

export type ManagerTypeEnum = (typeof managerTypeEnum)[keyof typeof managerTypeEnum]

export type ManagerType = ManagerTypeEnum