/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const MCPServerTypeEnum = {
  sse: 'sse',
  stdio: 'stdio',
} as const;

export type MCPServerTypeEnum =
  (typeof MCPServerTypeEnum)[keyof typeof MCPServerTypeEnum];

export type MCPServerType = MCPServerTypeEnum;
