/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description A simple wrapper around MCP\'s tool definition (to avoid conflict with our own)
 */
export type MCPTool = {
  /**
   * @type string
   */
  name: string;
  description?: string | null;
  /**
   * @type object
   */
  inputSchema: {
    [key: string]: any;
  };
  [key: string]: any;
};
