/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Block } from './Block.ts';

/**
 * @description Represents the in-context memory (i.e. Core memory) of the agent. This includes both the `Block` objects (labelled by sections), as well as tools to edit the blocks.
 */
export type Memory = {
  /**
   * @description Memory blocks contained in the agent\'s in-context memory
   * @type array
   */
  blocks: Block[];
  /**
   * @description Jinja2 template for compiling memory blocks into a prompt string
   * @default "{% for block in blocks %}<{{ block.label }} characters=\"{{ block.value|length }}/{{ block.limit }}\">\n{{ block.value }}\n</{{ block.label }}>{% if not loop.last %}\n{% endif %}{% endfor %}"
   * @type string | undefined
   */
  prompt_template?: string;
};
