/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Block } from './Block.ts'
import type { BlockUpdate } from './BlockUpdate.ts'
import type { HTTPValidationError } from './HTTPValidationError.ts'

export type ModifyBlockPathParams = {
  /**
   * @type string
   */
  block_id: string
}

/**
 * @description Successful Response
 */
export type ModifyBlock200 = Block

/**
 * @description Validation Error
 */
export type ModifyBlock422 = HTTPValidationError

export type ModifyBlockMutationRequest = BlockUpdate

export type ModifyBlockMutationResponse = ModifyBlock200

export type ModifyBlockMutation = {
  Response: ModifyBlock200
  Request: ModifyBlockMutationRequest
  PathParams: ModifyBlockPathParams
  Errors: ModifyBlock422
}