/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const omittedReasoningContentTypeEnum = {
  omitted_reasoning: 'omitted_reasoning',
} as const;

export type OmittedReasoningContentTypeEnum =
  (typeof omittedReasoningContentTypeEnum)[keyof typeof omittedReasoningContentTypeEnum];

export type OmittedReasoningContent = {
  /**
   * @description Indicates this is an omitted reasoning step.
   * @default "omitted_reasoning"
   * @type string
   */
  type: OmittedReasoningContentTypeEnum;
  /**
   * @description The reasoning token count for intermediate reasoning content.
   * @type integer
   */
  tokens: number;
};
