/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type OpenaiTypesChatChatCompletionMessageToolCallParamFunction = {
  /**
   * @type string
   */
  arguments: string;
  /**
   * @type string
   */
  name: string;
};
