/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Organization = {
  /**
   * @description The human-friendly ID of the Org
   * @pattern ^org-[a-fA-F0-9]{8}
   * @type string | undefined
   */
  id?: string
  /**
   * @description The name of the organization.
   * @default "SincereYogurt"
   * @type string | undefined
   */
  name?: string
  /**
   * @description The creation date of the organization.
   */
  created_at?: string | null
  /**
   * @description Whether the organization has access to privileged tools.
   * @default false
   * @type boolean | undefined
   */
  privileged_tools?: boolean
}