/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description A ToolRule that only allows a child tool to be called if the parent has been called.
 */
export type ParentToolRule = {
  /**
   * @description The name of the tool. Must exist in the database for the user\'s organization.
   * @type string
   */
  tool_name: string;
  /**
   * @default "parent_last_tool"
   * @type string | undefined
   */
  type?: 'parent_last_tool';
  /**
   * @description The children tools that can be invoked.
   * @type array
   */
  children: string[];
};
