/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PipRequirement = {
  /**
   * @description Name of the pip package.
   * @minLength 1
   * @type string
   */
  name: string;
  /**
   * @description Optional version of the package, following semantic versioning.
   */
  version?: string | null;
};
