/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ProviderCreate = {
  /**
   * @description The name of the provider.
   * @type string
   */
  name: string;
  /**
   * @description API key used for requests to the provider.
   * @type string
   */
  api_key: string;
};
