/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const reasoningContentTypeEnum = {
  reasoning: 'reasoning',
} as const

export type ReasoningContentTypeEnum = (typeof reasoningContentTypeEnum)[keyof typeof reasoningContentTypeEnum]

export type ReasoningContent = {
  /**
   * @description Indicates this is a reasoning/intermediate step.
   * @default "reasoning"
   * @type string
   */
  type: ReasoningContentTypeEnum
  /**
   * @description Whether the reasoning content was generated by a reasoner model that processed this step.
   * @type boolean
   */
  is_native: boolean
  /**
   * @description The intermediate reasoning or thought process content.
   * @type string
   */
  reasoning: string
  /**
   * @description A unique identifier for this reasoning step.
   */
  signature?: string | null
}