/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from './HTTPValidationError.ts'
import type { Step } from './Step.ts'

export type RetrieveStepPathParams = {
  /**
   * @type string
   */
  step_id: string
}

/**
 * @description Successful Response
 */
export type RetrieveStep200 = Step

/**
 * @description Validation Error
 */
export type RetrieveStep422 = HTTPValidationError

export type RetrieveStepQueryResponse = RetrieveStep200

export type RetrieveStepQuery = {
  Response: RetrieveStep200
  PathParams: RetrieveStepPathParams
  Errors: RetrieveStep422
}