/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from './HTTPValidationError.ts';
import type { Identity } from './Identity.ts';

export type RetrieveIdentityPathParams = {
  /**
   * @type string
   */
  identity_id: string;
};

/**
 * @description Successful Response
 */
export type RetrieveIdentity200 = Identity;

/**
 * @description Validation Error
 */
export type RetrieveIdentity422 = HTTPValidationError;

export type RetrieveIdentityQueryResponse = RetrieveIdentity200;

export type RetrieveIdentityQuery = {
  Response: RetrieveIdentity200;
  PathParams: RetrieveIdentityPathParams;
  Errors: RetrieveIdentity422;
};
