/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type RoundRobinManagerUpdate = {
  /**
   * @default "round_robin"
   * @type string | undefined
   */
  manager_type?: 'round_robin';
  max_turns?: number | null;
};
