/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const sandboxTypeEnum = {
  e2b: 'e2b',
  local: 'local',
} as const;

export type SandboxTypeEnum =
  (typeof sandboxTypeEnum)[keyof typeof sandboxTypeEnum];

export type SandboxType = SandboxTypeEnum;
