/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SleeptimeManagerUpdate = {
  /**
   * @default "sleeptime"
   * @type string | undefined
   */
  manager_type?: 'sleeptime'
  manager_agent_id?: string | null
  sleeptime_agent_frequency?: number | null
}