/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EmbeddingConfig } from './EmbeddingConfig.ts';

/**
 * @description Schema for creating a new Source.
 */
export type SourceCreate = {
  /**
   * @description The name of the source.
   * @type string
   */
  name: string;
  /**
   * @description The hande for the embedding config used by the source.
   */
  embedding?: string | null;
  /**
   * @description The chunk size of the embedding.
   */
  embedding_chunk_size?: number | null;
  /**
   * @description (Legacy) The embedding configuration used by the source.
   */
  embedding_config?: EmbeddingConfig | null;
  /**
   * @description The description of the source.
   */
  description?: string | null;
  /**
   * @description Metadata associated with the source.
   */
  metadata?: {
    [key: string]: any;
  } | null;
};
