/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SupervisorManagerUpdate = {
  /**
   * @default "supervisor"
   * @type string | undefined
   */
  manager_type?: 'supervisor'
  manager_agent_id: string | null
}