/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ToolEnvVarSchema = {
  /**
   * @type string
   */
  created_at: string;
  description: string | null;
  /**
   * @type string
   */
  key: string;
  /**
   * @type string
   */
  updated_at: string;
  /**
   * @type string
   */
  value: string;
};
