/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ToolCall = {
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  arguments: string;
  /**
   * @type string
   */
  tool_call_id: string;
};
