/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const toolTypeEnum = {
  custom: 'custom',
  letta_core: 'letta_core',
  letta_memory_core: 'letta_memory_core',
  letta_multi_agent_core: 'letta_multi_agent_core',
  letta_sleeptime_core: 'letta_sleeptime_core',
  external_composio: 'external_composio',
  external_langchain: 'external_langchain',
  external_mcp: 'external_mcp',
} as const;

export type ToolTypeEnum = (typeof toolTypeEnum)[keyof typeof toolTypeEnum];

export type ToolType = ToolTypeEnum;
