/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToolCall } from './ToolCall.ts'
import type { ToolCallDelta } from './ToolCallDelta.ts'

export const toolCallMessageMessageTypeEnum = {
  tool_call_message: 'tool_call_message',
} as const

export type ToolCallMessageMessageTypeEnum = (typeof toolCallMessageMessageTypeEnum)[keyof typeof toolCallMessageMessageTypeEnum]

/**
 * @description A message representing a request to call a tool (generated by the LLM to trigger tool execution).\n\nArgs:\n    id (str): The ID of the message\n    date (datetime): The date the message was created in ISO format\n    name (Optional[str]): The name of the sender of the message\n    tool_call (Union[ToolCall, ToolCallDelta]): The tool call
 */
export type ToolCallMessage = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string, date-time
   */
  date: string
  name?: string | null
  otid?: string | null
  /**
   * @default "tool_call_message"
   * @type string
   */
  message_type: ToolCallMessageMessageTypeEnum
  tool_call: ToolCall | ToolCallDelta
}