/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const toolReturnMessageMessageTypeEnum = {
  tool_return_message: 'tool_return_message',
} as const;

export type ToolReturnMessageMessageTypeEnum =
  (typeof toolReturnMessageMessageTypeEnum)[keyof typeof toolReturnMessageMessageTypeEnum];

export const toolReturnMessageStatusEnum = {
  success: 'success',
  error: 'error',
} as const;

export type ToolReturnMessageStatusEnum =
  (typeof toolReturnMessageStatusEnum)[keyof typeof toolReturnMessageStatusEnum];

/**
 * @description A message representing the return value of a tool call (generated by Letta executing the requested tool).\n\nArgs:\n    id (str): The ID of the message\n    date (datetime): The date the message was created in ISO format\n    name (Optional[str]): The name of the sender of the message\n    tool_return (str): The return value of the tool\n    status (Literal[\"success\", \"error\"]): The status of the tool call\n    tool_call_id (str): A unique identifier for the tool call that generated this message\n    stdout (Optional[List(str)]): Captured stdout (e.g. prints, logs) from the tool invocation\n    stderr (Optional[List(str)]): Captured stderr from the tool invocation
 */
export type ToolReturnMessage = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string, date-time
   */
  date: string;
  name?: string | null;
  otid?: string | null;
  /**
   * @default "tool_return_message"
   * @type string
   */
  message_type: ToolReturnMessageMessageTypeEnum;
  /**
   * @type string
   */
  tool_return: string;
  /**
   * @type string
   */
  status: ToolReturnMessageStatusEnum;
  /**
   * @type string
   */
  tool_call_id: string;
  stdout?: string[] | null;
  stderr?: string[] | null;
};
