/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const toolReturnStatusEnum = {
  success: 'success',
  error: 'error',
} as const

export type ToolReturnStatusEnum = (typeof toolReturnStatusEnum)[keyof typeof toolReturnStatusEnum]

export type ToolReturn = {
  /**
   * @description The status of the tool call
   * @type string
   */
  status: ToolReturnStatusEnum
  /**
   * @description Captured stdout (e.g. prints, logs) from the tool invocation
   */
  stdout?: string[] | null
  /**
   * @description Captured stderr from the tool invocation
   */
  stderr?: string[] | null
}