/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UsageStatistics = {
  /**
   * @default 0
   * @type integer | undefined
   */
  completion_tokens?: number
  /**
   * @default 0
   * @type integer | undefined
   */
  prompt_tokens?: number
  /**
   * @default 0
   * @type integer | undefined
   */
  total_tokens?: number
}