/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Representation of a user.\n\nParameters:\n    id (str): The unique identifier of the user.\n    name (str): The name of the user.\n    created_at (datetime): The creation date of the user.
 */
export type User = {
  /**
   * @description The human-friendly ID of the User
   * @pattern ^user-[a-fA-F0-9]{8}
   * @type string | undefined
   */
  id?: string;
  /**
   * @description The name of the user.
   * @type string
   */
  name: string;
  /**
   * @description The creation date of the user.
   */
  created_at?: string | null;
  /**
   * @description The update date of the user.
   */
  updated_at?: string | null;
  /**
   * @description Whether this user is deleted or not.
   * @default false
   * @type boolean | undefined
   */
  is_deleted?: boolean;
};
