/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type { ListModelsQueryResponse } from '../../types/ListModels.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  InfiniteQueryObserverOptions,
  UseInfiniteQueryResult,
} from '@tanstack/react-query';
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query';

export const listModelsInfiniteQueryKey = () =>
  [{ url: '/v1/models/' }] as const;

export type ListModelsInfiniteQueryKey = ReturnType<
  typeof listModelsInfiniteQueryKey
>;

/**
 * @summary List Llm Backends
 * {@link /v1/models/}
 */
export async function listModelsInfinite(
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    ListModelsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/v1/models/`, ...requestConfig });
  return res;
}

export function listModelsInfiniteQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = listModelsInfiniteQueryKey();
  return infiniteQueryOptions<
    ResponseConfig<ListModelsQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<ListModelsQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listModelsInfinite(config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  });
}

/**
 * @summary List Llm Backends
 * {@link /v1/models/}
 */
export function useListModelsInfinite<
  TData = InfiniteData<ResponseConfig<ListModelsQueryResponse>>,
  TQueryData = ResponseConfig<ListModelsQueryResponse>,
  TQueryKey extends QueryKey = ListModelsInfiniteQueryKey
>(
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<ListModelsQueryResponse>,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? listModelsInfiniteQueryKey();

  const query = useInfiniteQuery(
    {
      ...(listModelsInfiniteQueryOptions(
        config
      ) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<
        InfiniteQueryObserverOptions,
        'queryKey'
      >),
    },
    queryClient
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
