/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { ListStepsQueryResponse, ListStepsQueryParams, ListSteps422 } from '../../types/ListSteps.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const listStepsSuspenseQueryKey = (params?: ListStepsQueryParams) => [{ url: '/v1/steps' }, ...(params ? [params] : [])] as const

export type ListStepsSuspenseQueryKey = ReturnType<typeof listStepsSuspenseQueryKey>

/**
 * @description List steps with optional pagination and date filters.Dates should be provided in ISO 8601 format (e.g. 2025-01-29T15:01:19-08:00)
 * @summary List Steps
 * {@link /v1/steps}
 */
export async function listStepsSuspense(params?: ListStepsQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<ListStepsQueryResponse, ResponseErrorConfig<ListSteps422>, unknown>({ method: 'GET', url: `/v1/steps`, params, ...requestConfig })
  return res
}

export function listStepsSuspenseQueryOptions(params?: ListStepsQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = listStepsSuspenseQueryKey(params)
  return queryOptions<ResponseConfig<ListStepsQueryResponse>, ResponseErrorConfig<ListSteps422>, ResponseConfig<ListStepsQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return listStepsSuspense(params, config)
    },
  })
}

/**
 * @description List steps with optional pagination and date filters.Dates should be provided in ISO 8601 format (e.g. 2025-01-29T15:01:19-08:00)
 * @summary List Steps
 * {@link /v1/steps}
 */
export function useListStepsSuspense<
  TData = ResponseConfig<ListStepsQueryResponse>,
  TQueryData = ResponseConfig<ListStepsQueryResponse>,
  TQueryKey extends QueryKey = ListStepsSuspenseQueryKey,
>(
  params?: ListStepsQueryParams,
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<ListStepsQueryResponse>, ResponseErrorConfig<ListSteps422>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? listStepsSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...(listStepsSuspenseQueryOptions(params, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ListSteps422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}