/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  ListIdentitiesQueryResponse,
  ListIdentitiesQueryParams,
  ListIdentities422,
} from '../../types/ListIdentities.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';

export const listIdentitiesSuspenseQueryKey = (
  params?: ListIdentitiesQueryParams
) => [{ url: '/v1/identities/' }, ...(params ? [params] : [])] as const;

export type ListIdentitiesSuspenseQueryKey = ReturnType<
  typeof listIdentitiesSuspenseQueryKey
>;

/**
 * @description Get a list of all identities in the database
 * @summary List Identities
 * {@link /v1/identities/}
 */
export async function listIdentitiesSuspense(
  params?: ListIdentitiesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    ListIdentitiesQueryResponse,
    ResponseErrorConfig<ListIdentities422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/identities/`,
    params,
    ...requestConfig,
  });
  return res;
}

export function listIdentitiesSuspenseQueryOptions(
  params?: ListIdentitiesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = listIdentitiesSuspenseQueryKey(params);
  return queryOptions<
    ResponseConfig<ListIdentitiesQueryResponse>,
    ResponseErrorConfig<ListIdentities422>,
    ResponseConfig<ListIdentitiesQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listIdentitiesSuspense(params, config);
    },
  });
}

/**
 * @description Get a list of all identities in the database
 * @summary List Identities
 * {@link /v1/identities/}
 */
export function useListIdentitiesSuspense<
  TData = ResponseConfig<ListIdentitiesQueryResponse>,
  TQueryData = ResponseConfig<ListIdentitiesQueryResponse>,
  TQueryKey extends QueryKey = ListIdentitiesSuspenseQueryKey
>(
  params?: ListIdentitiesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ResponseConfig<ListIdentitiesQueryResponse>,
        ResponseErrorConfig<ListIdentities422>,
        TData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? listIdentitiesSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...(listIdentitiesSuspenseQueryOptions(
        params,
        config
      ) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ListIdentities422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
