/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  RetrieveIdentityQueryResponse,
  RetrieveIdentityPathParams,
  RetrieveIdentity422,
} from '../../types/RetrieveIdentity.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  InfiniteQueryObserverOptions,
  UseInfiniteQueryResult,
} from '@tanstack/react-query';
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query';

export const retrieveIdentityInfiniteQueryKey = (
  identity_id: RetrieveIdentityPathParams['identity_id']
) =>
  [
    {
      url: '/v1/identities/:identity_id',
      params: { identity_id: identity_id },
    },
  ] as const;

export type RetrieveIdentityInfiniteQueryKey = ReturnType<
  typeof retrieveIdentityInfiniteQueryKey
>;

/**
 * @summary Retrieve Identity
 * {@link /v1/identities/:identity_id}
 */
export async function retrieveIdentityInfinite(
  identity_id: RetrieveIdentityPathParams['identity_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    RetrieveIdentityQueryResponse,
    ResponseErrorConfig<RetrieveIdentity422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/identities/${identity_id}`,
    ...requestConfig,
  });
  return res;
}

export function retrieveIdentityInfiniteQueryOptions(
  identity_id: RetrieveIdentityPathParams['identity_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = retrieveIdentityInfiniteQueryKey(identity_id);
  return infiniteQueryOptions<
    ResponseConfig<RetrieveIdentityQueryResponse>,
    ResponseErrorConfig<RetrieveIdentity422>,
    ResponseConfig<RetrieveIdentityQueryResponse>,
    typeof queryKey
  >({
    enabled: !!identity_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return retrieveIdentityInfinite(identity_id, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  });
}

/**
 * @summary Retrieve Identity
 * {@link /v1/identities/:identity_id}
 */
export function useRetrieveIdentityInfinite<
  TData = InfiniteData<ResponseConfig<RetrieveIdentityQueryResponse>>,
  TQueryData = ResponseConfig<RetrieveIdentityQueryResponse>,
  TQueryKey extends QueryKey = RetrieveIdentityInfiniteQueryKey
>(
  identity_id: RetrieveIdentityPathParams['identity_id'],
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<RetrieveIdentityQueryResponse>,
        ResponseErrorConfig<RetrieveIdentity422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? retrieveIdentityInfiniteQueryKey(identity_id);

  const query = useInfiniteQuery(
    {
      ...(retrieveIdentityInfiniteQueryOptions(
        identity_id,
        config
      ) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<
        InfiniteQueryObserverOptions,
        'queryKey'
      >),
    },
    queryClient
  ) as UseInfiniteQueryResult<
    TData,
    ResponseErrorConfig<RetrieveIdentity422>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
