/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  DeleteGroupMutationResponse,
  DeleteGroupPathParams,
  DeleteGroup422,
} from '../../types/DeleteGroup.ts';
import type {
  RequestConfig,
  ResponseConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query';
import { useMutation } from '@tanstack/react-query';

export const deleteGroupMutationKey = () =>
  [{ url: '/v1/groups/{group_id}' }] as const;

export type DeleteGroupMutationKey = ReturnType<typeof deleteGroupMutationKey>;

/**
 * @description Delete a multi-agent group.
 * @summary Delete Group
 * {@link /v1/groups/:group_id}
 */
export async function deleteGroup(
  group_id: DeleteGroupPathParams['group_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    DeleteGroupMutationResponse,
    ResponseErrorConfig<DeleteGroup422>,
    unknown
  >({
    method: 'DELETE',
    url: `/v1/groups/${group_id}`,
    ...requestConfig,
  });
  return res;
}

/**
 * @description Delete a multi-agent group.
 * @summary Delete Group
 * {@link /v1/groups/:group_id}
 */
export function useDeleteGroup<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<DeleteGroupMutationResponse>,
      ResponseErrorConfig<DeleteGroup422>,
      { group_id: DeleteGroupPathParams['group_id'] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    mutation: { client: queryClient, ...mutationOptions } = {},
    client: config = {},
  } = options ?? {};
  const mutationKey = mutationOptions?.mutationKey ?? deleteGroupMutationKey();

  return useMutation<
    ResponseConfig<DeleteGroupMutationResponse>,
    ResponseErrorConfig<DeleteGroup422>,
    { group_id: DeleteGroupPathParams['group_id'] },
    TContext
  >(
    {
      mutationFn: async ({ group_id }) => {
        return deleteGroup(group_id, config);
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  );
}
