/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  ListGroupsQueryResponse,
  ListGroupsQueryParams,
  ListGroups422,
} from '../../types/ListGroups.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';

export const listGroupsSuspenseQueryKey = (params?: ListGroupsQueryParams) =>
  [{ url: '/v1/groups/' }, ...(params ? [params] : [])] as const;

export type ListGroupsSuspenseQueryKey = ReturnType<
  typeof listGroupsSuspenseQueryKey
>;

/**
 * @description Fetch all multi-agent groups matching query.
 * @summary List Groups
 * {@link /v1/groups/}
 */
export async function listGroupsSuspense(
  params?: ListGroupsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    ListGroupsQueryResponse,
    ResponseErrorConfig<ListGroups422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/groups/`,
    params,
    ...requestConfig,
  });
  return res;
}

export function listGroupsSuspenseQueryOptions(
  params?: ListGroupsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = listGroupsSuspenseQueryKey(params);
  return queryOptions<
    ResponseConfig<ListGroupsQueryResponse>,
    ResponseErrorConfig<ListGroups422>,
    ResponseConfig<ListGroupsQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listGroupsSuspense(params, config);
    },
  });
}

/**
 * @description Fetch all multi-agent groups matching query.
 * @summary List Groups
 * {@link /v1/groups/}
 */
export function useListGroupsSuspense<
  TData = ResponseConfig<ListGroupsQueryResponse>,
  TQueryData = ResponseConfig<ListGroupsQueryResponse>,
  TQueryKey extends QueryKey = ListGroupsSuspenseQueryKey
>(
  params?: ListGroupsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ResponseConfig<ListGroupsQueryResponse>,
        ResponseErrorConfig<ListGroups422>,
        TData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? listGroupsSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...(listGroupsSuspenseQueryOptions(
        params,
        config
      ) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ListGroups422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
