/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  ListActiveJobsQueryResponse,
  ListActiveJobs422,
} from '../../types/ListActiveJobs.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  InfiniteQueryObserverOptions,
  UseInfiniteQueryResult,
} from '@tanstack/react-query';
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query';

export const listActiveJobsInfiniteQueryKey = () =>
  [{ url: '/v1/jobs/active' }] as const;

export type ListActiveJobsInfiniteQueryKey = ReturnType<
  typeof listActiveJobsInfiniteQueryKey
>;

/**
 * @description List all active jobs.
 * @summary List Active Jobs
 * {@link /v1/jobs/active}
 */
export async function listActiveJobsInfinite(
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    ListActiveJobsQueryResponse,
    ResponseErrorConfig<ListActiveJobs422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/jobs/active`,
    ...requestConfig,
  });
  return res;
}

export function listActiveJobsInfiniteQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = listActiveJobsInfiniteQueryKey();
  return infiniteQueryOptions<
    ResponseConfig<ListActiveJobsQueryResponse>,
    ResponseErrorConfig<ListActiveJobs422>,
    ResponseConfig<ListActiveJobsQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listActiveJobsInfinite(config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  });
}

/**
 * @description List all active jobs.
 * @summary List Active Jobs
 * {@link /v1/jobs/active}
 */
export function useListActiveJobsInfinite<
  TData = InfiniteData<ResponseConfig<ListActiveJobsQueryResponse>>,
  TQueryData = ResponseConfig<ListActiveJobsQueryResponse>,
  TQueryKey extends QueryKey = ListActiveJobsInfiniteQueryKey
>(
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<ListActiveJobsQueryResponse>,
        ResponseErrorConfig<ListActiveJobs422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? listActiveJobsInfiniteQueryKey();

  const query = useInfiniteQuery(
    {
      ...(listActiveJobsInfiniteQueryOptions(
        config
      ) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<
        InfiniteQueryObserverOptions,
        'queryKey'
      >),
    },
    queryClient
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<ListActiveJobs422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
