/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  RetrieveJobQueryResponse,
  RetrieveJobPathParams,
  RetrieveJob422,
} from '../../types/RetrieveJob.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  InfiniteQueryObserverOptions,
  UseInfiniteQueryResult,
} from '@tanstack/react-query';
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query';

export const retrieveJobInfiniteQueryKey = (
  job_id: RetrieveJobPathParams['job_id']
) => [{ url: '/v1/jobs/:job_id', params: { job_id: job_id } }] as const;

export type RetrieveJobInfiniteQueryKey = ReturnType<
  typeof retrieveJobInfiniteQueryKey
>;

/**
 * @description Get the status of a job.
 * @summary Retrieve Job
 * {@link /v1/jobs/:job_id}
 */
export async function retrieveJobInfinite(
  job_id: RetrieveJobPathParams['job_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    RetrieveJobQueryResponse,
    ResponseErrorConfig<RetrieveJob422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/jobs/${job_id}`,
    ...requestConfig,
  });
  return res;
}

export function retrieveJobInfiniteQueryOptions(
  job_id: RetrieveJobPathParams['job_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = retrieveJobInfiniteQueryKey(job_id);
  return infiniteQueryOptions<
    ResponseConfig<RetrieveJobQueryResponse>,
    ResponseErrorConfig<RetrieveJob422>,
    ResponseConfig<RetrieveJobQueryResponse>,
    typeof queryKey
  >({
    enabled: !!job_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return retrieveJobInfinite(job_id, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  });
}

/**
 * @description Get the status of a job.
 * @summary Retrieve Job
 * {@link /v1/jobs/:job_id}
 */
export function useRetrieveJobInfinite<
  TData = InfiniteData<ResponseConfig<RetrieveJobQueryResponse>>,
  TQueryData = ResponseConfig<RetrieveJobQueryResponse>,
  TQueryKey extends QueryKey = RetrieveJobInfiniteQueryKey
>(
  job_id: RetrieveJobPathParams['job_id'],
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<RetrieveJobQueryResponse>,
        ResponseErrorConfig<RetrieveJob422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? retrieveJobInfiniteQueryKey(job_id);

  const query = useInfiniteQuery(
    {
      ...(retrieveJobInfiniteQueryOptions(
        job_id,
        config
      ) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<
        InfiniteQueryObserverOptions,
        'queryKey'
      >),
    },
    queryClient
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<RetrieveJob422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
