/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { ListTagsQueryResponse, ListTagsQueryParams, ListTags422 } from '../../types/ListTags.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const listTagsSuspenseQueryKey = (params?: ListTagsQueryParams) => [{ url: '/v1/tags/' }, ...(params ? [params] : [])] as const

export type ListTagsSuspenseQueryKey = ReturnType<typeof listTagsSuspenseQueryKey>

/**
 * @description Get a list of all tags in the database
 * @summary List Tags
 * {@link /v1/tags/}
 */
export async function listTagsSuspense(params?: ListTagsQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<ListTagsQueryResponse, ResponseErrorConfig<ListTags422>, unknown>({ method: 'GET', url: `/v1/tags/`, params, ...requestConfig })
  return res
}

export function listTagsSuspenseQueryOptions(params?: ListTagsQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = listTagsSuspenseQueryKey(params)
  return queryOptions<ResponseConfig<ListTagsQueryResponse>, ResponseErrorConfig<ListTags422>, ResponseConfig<ListTagsQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return listTagsSuspense(params, config)
    },
  })
}

/**
 * @description Get a list of all tags in the database
 * @summary List Tags
 * {@link /v1/tags/}
 */
export function useListTagsSuspense<
  TData = ResponseConfig<ListTagsQueryResponse>,
  TQueryData = ResponseConfig<ListTagsQueryResponse>,
  TQueryKey extends QueryKey = ListTagsSuspenseQueryKey,
>(
  params?: ListTagsQueryParams,
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<ListTagsQueryResponse>, ResponseErrorConfig<ListTags422>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? listTagsSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...(listTagsSuspenseQueryOptions(params, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ListTags422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}