/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  ListTagsQueryResponse,
  ListTagsQueryParams,
  ListTags422,
} from '../../types/ListTags.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  InfiniteQueryObserverOptions,
  UseInfiniteQueryResult,
} from '@tanstack/react-query';
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query';

export const listTagsInfiniteQueryKey = (params?: ListTagsQueryParams) =>
  [{ url: '/v1/tags/' }, ...(params ? [params] : [])] as const;

export type ListTagsInfiniteQueryKey = ReturnType<
  typeof listTagsInfiniteQueryKey
>;

/**
 * @description Get a list of all tags in the database
 * @summary List Tags
 * {@link /v1/tags/}
 */
export async function listTagsInfinite(
  params?: ListTagsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    ListTagsQueryResponse,
    ResponseErrorConfig<ListTags422>,
    unknown
  >({ method: 'GET', url: `/v1/tags/`, params, ...requestConfig });
  return res;
}

export function listTagsInfiniteQueryOptions(
  params?: ListTagsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = listTagsInfiniteQueryKey(params);
  return infiniteQueryOptions<
    ResponseConfig<ListTagsQueryResponse>,
    ResponseErrorConfig<ListTags422>,
    ResponseConfig<ListTagsQueryResponse>,
    typeof queryKey,
    number
  >({
    queryKey,
    queryFn: async ({ signal, pageParam }) => {
      config.signal = signal;

      if (params) {
        params['next_page'] =
          pageParam as unknown as ListTagsQueryParams['next_page'];
      }
      return listTagsInfinite(params, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  });
}

/**
 * @description Get a list of all tags in the database
 * @summary List Tags
 * {@link /v1/tags/}
 */
export function useListTagsInfinite<
  TData = InfiniteData<ResponseConfig<ListTagsQueryResponse>>,
  TQueryData = ResponseConfig<ListTagsQueryResponse>,
  TQueryKey extends QueryKey = ListTagsInfiniteQueryKey
>(
  params?: ListTagsQueryParams,
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<ListTagsQueryResponse>,
        ResponseErrorConfig<ListTags422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? listTagsInfiniteQueryKey(params);

  const query = useInfiniteQuery(
    {
      ...(listTagsInfiniteQueryOptions(
        params,
        config
      ) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<
        InfiniteQueryObserverOptions,
        'queryKey'
      >),
    },
    queryClient
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<ListTags422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
