/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  ListProvidersQueryResponse,
  ListProvidersQueryParams,
  ListProviders422,
} from '../../types/ListProviders.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  InfiniteQueryObserverOptions,
  UseInfiniteQueryResult,
} from '@tanstack/react-query';
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query';

export const listProvidersInfiniteQueryKey = (
  params?: ListProvidersQueryParams
) => [{ url: '/v1/providers/' }, ...(params ? [params] : [])] as const;

export type ListProvidersInfiniteQueryKey = ReturnType<
  typeof listProvidersInfiniteQueryKey
>;

/**
 * @description Get a list of all custom providers in the database
 * @summary List Providers
 * {@link /v1/providers/}
 */
export async function listProvidersInfinite(
  params?: ListProvidersQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    ListProvidersQueryResponse,
    ResponseErrorConfig<ListProviders422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/providers/`,
    params,
    ...requestConfig,
  });
  return res;
}

export function listProvidersInfiniteQueryOptions(
  params?: ListProvidersQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = listProvidersInfiniteQueryKey(params);
  return infiniteQueryOptions<
    ResponseConfig<ListProvidersQueryResponse>,
    ResponseErrorConfig<ListProviders422>,
    ResponseConfig<ListProvidersQueryResponse>,
    typeof queryKey,
    number
  >({
    queryKey,
    queryFn: async ({ signal, pageParam }) => {
      config.signal = signal;

      if (params) {
        params['next_page'] =
          pageParam as unknown as ListProvidersQueryParams['next_page'];
      }
      return listProvidersInfinite(params, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  });
}

/**
 * @description Get a list of all custom providers in the database
 * @summary List Providers
 * {@link /v1/providers/}
 */
export function useListProvidersInfinite<
  TData = InfiniteData<ResponseConfig<ListProvidersQueryResponse>>,
  TQueryData = ResponseConfig<ListProvidersQueryResponse>,
  TQueryKey extends QueryKey = ListProvidersInfiniteQueryKey
>(
  params?: ListProvidersQueryParams,
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<ListProvidersQueryResponse>,
        ResponseErrorConfig<ListProviders422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? listProvidersInfiniteQueryKey(params);

  const query = useInfiniteQuery(
    {
      ...(listProvidersInfiniteQueryOptions(
        params,
        config
      ) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<
        InfiniteQueryObserverOptions,
        'queryKey'
      >),
    },
    queryClient
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<ListProviders422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
