/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  GetSourceIdByNameQueryResponse,
  GetSourceIdByNamePathParams,
  GetSourceIdByName422,
} from '../../types/GetSourceIdByName.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  InfiniteQueryObserverOptions,
  UseInfiniteQueryResult,
} from '@tanstack/react-query';
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query';

export const getSourceIdByNameInfiniteQueryKey = (
  source_name: GetSourceIdByNamePathParams['source_name']
) =>
  [
    {
      url: '/v1/sources/name/:source_name',
      params: { source_name: source_name },
    },
  ] as const;

export type GetSourceIdByNameInfiniteQueryKey = ReturnType<
  typeof getSourceIdByNameInfiniteQueryKey
>;

/**
 * @description Get a source by name
 * @summary Get Source Id By Name
 * {@link /v1/sources/name/:source_name}
 */
export async function getSourceIdByNameInfinite(
  source_name: GetSourceIdByNamePathParams['source_name'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    GetSourceIdByNameQueryResponse,
    ResponseErrorConfig<GetSourceIdByName422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/sources/name/${source_name}`,
    ...requestConfig,
  });
  return res;
}

export function getSourceIdByNameInfiniteQueryOptions(
  source_name: GetSourceIdByNamePathParams['source_name'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = getSourceIdByNameInfiniteQueryKey(source_name);
  return infiniteQueryOptions<
    ResponseConfig<GetSourceIdByNameQueryResponse>,
    ResponseErrorConfig<GetSourceIdByName422>,
    ResponseConfig<GetSourceIdByNameQueryResponse>,
    typeof queryKey
  >({
    enabled: !!source_name,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getSourceIdByNameInfinite(source_name, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  });
}

/**
 * @description Get a source by name
 * @summary Get Source Id By Name
 * {@link /v1/sources/name/:source_name}
 */
export function useGetSourceIdByNameInfinite<
  TData = InfiniteData<ResponseConfig<GetSourceIdByNameQueryResponse>>,
  TQueryData = ResponseConfig<GetSourceIdByNameQueryResponse>,
  TQueryKey extends QueryKey = GetSourceIdByNameInfiniteQueryKey
>(
  source_name: GetSourceIdByNamePathParams['source_name'],
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<GetSourceIdByNameQueryResponse>,
        ResponseErrorConfig<GetSourceIdByName422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? getSourceIdByNameInfiniteQueryKey(source_name);

  const query = useInfiniteQuery(
    {
      ...(getSourceIdByNameInfiniteQueryOptions(
        source_name,
        config
      ) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<
        InfiniteQueryObserverOptions,
        'queryKey'
      >),
    },
    queryClient
  ) as UseInfiniteQueryResult<
    TData,
    ResponseErrorConfig<GetSourceIdByName422>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
