/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  ListSourcePassagesQueryResponse,
  ListSourcePassagesPathParams,
  ListSourcePassages422,
} from '../../types/ListSourcePassages.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  InfiniteQueryObserverOptions,
  UseInfiniteQueryResult,
} from '@tanstack/react-query';
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query';

export const listSourcePassagesInfiniteQueryKey = (
  source_id: ListSourcePassagesPathParams['source_id']
) =>
  [
    {
      url: '/v1/sources/:source_id/passages',
      params: { source_id: source_id },
    },
  ] as const;

export type ListSourcePassagesInfiniteQueryKey = ReturnType<
  typeof listSourcePassagesInfiniteQueryKey
>;

/**
 * @description List all passages associated with a data source.
 * @summary List Source Passages
 * {@link /v1/sources/:source_id/passages}
 */
export async function listSourcePassagesInfinite(
  source_id: ListSourcePassagesPathParams['source_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    ListSourcePassagesQueryResponse,
    ResponseErrorConfig<ListSourcePassages422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/sources/${source_id}/passages`,
    ...requestConfig,
  });
  return res;
}

export function listSourcePassagesInfiniteQueryOptions(
  source_id: ListSourcePassagesPathParams['source_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = listSourcePassagesInfiniteQueryKey(source_id);
  return infiniteQueryOptions<
    ResponseConfig<ListSourcePassagesQueryResponse>,
    ResponseErrorConfig<ListSourcePassages422>,
    ResponseConfig<ListSourcePassagesQueryResponse>,
    typeof queryKey
  >({
    enabled: !!source_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listSourcePassagesInfinite(source_id, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  });
}

/**
 * @description List all passages associated with a data source.
 * @summary List Source Passages
 * {@link /v1/sources/:source_id/passages}
 */
export function useListSourcePassagesInfinite<
  TData = InfiniteData<ResponseConfig<ListSourcePassagesQueryResponse>>,
  TQueryData = ResponseConfig<ListSourcePassagesQueryResponse>,
  TQueryKey extends QueryKey = ListSourcePassagesInfiniteQueryKey
>(
  source_id: ListSourcePassagesPathParams['source_id'],
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<ListSourcePassagesQueryResponse>,
        ResponseErrorConfig<ListSourcePassages422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? listSourcePassagesInfiniteQueryKey(source_id);

  const query = useInfiniteQuery(
    {
      ...(listSourcePassagesInfiniteQueryOptions(
        source_id,
        config
      ) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<
        InfiniteQueryObserverOptions,
        'queryKey'
      >),
    },
    queryClient
  ) as UseInfiniteQueryResult<
    TData,
    ResponseErrorConfig<ListSourcePassages422>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
