/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  RetrieveSourceQueryResponse,
  RetrieveSourcePathParams,
  RetrieveSource422,
} from '../../types/RetrieveSource.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  InfiniteQueryObserverOptions,
  UseInfiniteQueryResult,
} from '@tanstack/react-query';
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query';

export const retrieveSourceInfiniteQueryKey = (
  source_id: RetrieveSourcePathParams['source_id']
) =>
  [
    { url: '/v1/sources/:source_id', params: { source_id: source_id } },
  ] as const;

export type RetrieveSourceInfiniteQueryKey = ReturnType<
  typeof retrieveSourceInfiniteQueryKey
>;

/**
 * @description Get all sources
 * @summary Retrieve Source
 * {@link /v1/sources/:source_id}
 */
export async function retrieveSourceInfinite(
  source_id: RetrieveSourcePathParams['source_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    RetrieveSourceQueryResponse,
    ResponseErrorConfig<RetrieveSource422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/sources/${source_id}`,
    ...requestConfig,
  });
  return res;
}

export function retrieveSourceInfiniteQueryOptions(
  source_id: RetrieveSourcePathParams['source_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = retrieveSourceInfiniteQueryKey(source_id);
  return infiniteQueryOptions<
    ResponseConfig<RetrieveSourceQueryResponse>,
    ResponseErrorConfig<RetrieveSource422>,
    ResponseConfig<RetrieveSourceQueryResponse>,
    typeof queryKey
  >({
    enabled: !!source_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return retrieveSourceInfinite(source_id, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  });
}

/**
 * @description Get all sources
 * @summary Retrieve Source
 * {@link /v1/sources/:source_id}
 */
export function useRetrieveSourceInfinite<
  TData = InfiniteData<ResponseConfig<RetrieveSourceQueryResponse>>,
  TQueryData = ResponseConfig<RetrieveSourceQueryResponse>,
  TQueryKey extends QueryKey = RetrieveSourceInfiniteQueryKey
>(
  source_id: RetrieveSourcePathParams['source_id'],
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<RetrieveSourceQueryResponse>,
        ResponseErrorConfig<RetrieveSource422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? retrieveSourceInfiniteQueryKey(source_id);

  const query = useInfiniteQuery(
    {
      ...(retrieveSourceInfiniteQueryOptions(
        source_id,
        config
      ) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<
        InfiniteQueryObserverOptions,
        'queryKey'
      >),
    },
    queryClient
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<RetrieveSource422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
