/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  RetrieveSourceQueryResponse,
  RetrieveSourcePathParams,
  RetrieveSource422,
} from '../../types/RetrieveSource.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';

export const retrieveSourceSuspenseQueryKey = (
  source_id: RetrieveSourcePathParams['source_id']
) =>
  [
    { url: '/v1/sources/:source_id', params: { source_id: source_id } },
  ] as const;

export type RetrieveSourceSuspenseQueryKey = ReturnType<
  typeof retrieveSourceSuspenseQueryKey
>;

/**
 * @description Get all sources
 * @summary Retrieve Source
 * {@link /v1/sources/:source_id}
 */
export async function retrieveSourceSuspense(
  source_id: RetrieveSourcePathParams['source_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    RetrieveSourceQueryResponse,
    ResponseErrorConfig<RetrieveSource422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/sources/${source_id}`,
    ...requestConfig,
  });
  return res;
}

export function retrieveSourceSuspenseQueryOptions(
  source_id: RetrieveSourcePathParams['source_id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = retrieveSourceSuspenseQueryKey(source_id);
  return queryOptions<
    ResponseConfig<RetrieveSourceQueryResponse>,
    ResponseErrorConfig<RetrieveSource422>,
    ResponseConfig<RetrieveSourceQueryResponse>,
    typeof queryKey
  >({
    enabled: !!source_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return retrieveSourceSuspense(source_id, config);
    },
  });
}

/**
 * @description Get all sources
 * @summary Retrieve Source
 * {@link /v1/sources/:source_id}
 */
export function useRetrieveSourceSuspense<
  TData = ResponseConfig<RetrieveSourceQueryResponse>,
  TQueryData = ResponseConfig<RetrieveSourceQueryResponse>,
  TQueryKey extends QueryKey = RetrieveSourceSuspenseQueryKey
>(
  source_id: RetrieveSourcePathParams['source_id'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ResponseConfig<RetrieveSourceQueryResponse>,
        ResponseErrorConfig<RetrieveSource422>,
        TData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? retrieveSourceSuspenseQueryKey(source_id);

  const query = useSuspenseQuery(
    {
      ...(retrieveSourceSuspenseQueryOptions(
        source_id,
        config
      ) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<RetrieveSource422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
