/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type { HealthCheckQueryResponse } from '../../types/HealthCheck.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const healthCheckQueryKey = () => [{ url: '/v1/health/' }] as const;

export type HealthCheckQueryKey = ReturnType<typeof healthCheckQueryKey>;

/**
 * @summary Health Check
 * {@link /v1/health/}
 */
export async function healthCheck(
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    HealthCheckQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/v1/health/`, ...requestConfig });
  return res;
}

export function healthCheckQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = healthCheckQueryKey();
  return queryOptions<
    ResponseConfig<HealthCheckQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<HealthCheckQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return healthCheck(config);
    },
  });
}

/**
 * @summary Health Check
 * {@link /v1/health/}
 */
export function useHealthCheck<
  TData = ResponseConfig<HealthCheckQueryResponse>,
  TQueryData = ResponseConfig<HealthCheckQueryResponse>,
  TQueryKey extends QueryKey = HealthCheckQueryKey
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        ResponseConfig<HealthCheckQueryResponse>,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? healthCheckQueryKey();

  const query = useQuery(
    {
      ...(healthCheckQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
