/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { ListToolsQueryResponse, ListToolsQueryParams, ListTools422 } from '../../types/ListTools.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const listToolsQueryKey = (params?: ListToolsQueryParams) => [{ url: '/v1/tools/' }, ...(params ? [params] : [])] as const

export type ListToolsQueryKey = ReturnType<typeof listToolsQueryKey>

/**
 * @description Get a list of all tools available to agents belonging to the org of the user
 * @summary List Tools
 * {@link /v1/tools/}
 */
export async function listTools(params?: ListToolsQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<ListToolsQueryResponse, ResponseErrorConfig<ListTools422>, unknown>({ method: 'GET', url: `/v1/tools/`, params, ...requestConfig })
  return res
}

export function listToolsQueryOptions(params?: ListToolsQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = listToolsQueryKey(params)
  return queryOptions<ResponseConfig<ListToolsQueryResponse>, ResponseErrorConfig<ListTools422>, ResponseConfig<ListToolsQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return listTools(params, config)
    },
  })
}

/**
 * @description Get a list of all tools available to agents belonging to the org of the user
 * @summary List Tools
 * {@link /v1/tools/}
 */
export function useListTools<
  TData = ResponseConfig<ListToolsQueryResponse>,
  TQueryData = ResponseConfig<ListToolsQueryResponse>,
  TQueryKey extends QueryKey = ListToolsQueryKey,
>(
  params?: ListToolsQueryParams,
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<ListToolsQueryResponse>, ResponseErrorConfig<ListTools422>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? listToolsQueryKey(params)

  const query = useQuery(
    {
      ...(listToolsQueryOptions(params, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<ListTools422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}