/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  ListMcpToolsByServerQueryResponse,
  ListMcpToolsByServerPathParams,
  ListMcpToolsByServer422,
} from '../../types/ListMcpToolsByServer.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  InfiniteQueryObserverOptions,
  UseInfiniteQueryResult,
} from '@tanstack/react-query';
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query';

export const listMcpToolsByServerInfiniteQueryKey = (
  mcp_server_name: ListMcpToolsByServerPathParams['mcp_server_name']
) =>
  [
    {
      url: '/v1/tools/mcp/servers/:mcp_server_name/tools',
      params: { mcp_server_name: mcp_server_name },
    },
  ] as const;

export type ListMcpToolsByServerInfiniteQueryKey = ReturnType<
  typeof listMcpToolsByServerInfiniteQueryKey
>;

/**
 * @description Get a list of all tools for a specific MCP server
 * @summary List Mcp Tools By Server
 * {@link /v1/tools/mcp/servers/:mcp_server_name/tools}
 */
export async function listMcpToolsByServerInfinite(
  mcp_server_name: ListMcpToolsByServerPathParams['mcp_server_name'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    ListMcpToolsByServerQueryResponse,
    ResponseErrorConfig<ListMcpToolsByServer422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/tools/mcp/servers/${mcp_server_name}/tools`,
    ...requestConfig,
  });
  return res;
}

export function listMcpToolsByServerInfiniteQueryOptions(
  mcp_server_name: ListMcpToolsByServerPathParams['mcp_server_name'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = listMcpToolsByServerInfiniteQueryKey(mcp_server_name);
  return infiniteQueryOptions<
    ResponseConfig<ListMcpToolsByServerQueryResponse>,
    ResponseErrorConfig<ListMcpToolsByServer422>,
    ResponseConfig<ListMcpToolsByServerQueryResponse>,
    typeof queryKey
  >({
    enabled: !!mcp_server_name,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listMcpToolsByServerInfinite(mcp_server_name, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  });
}

/**
 * @description Get a list of all tools for a specific MCP server
 * @summary List Mcp Tools By Server
 * {@link /v1/tools/mcp/servers/:mcp_server_name/tools}
 */
export function useListMcpToolsByServerInfinite<
  TData = InfiniteData<ResponseConfig<ListMcpToolsByServerQueryResponse>>,
  TQueryData = ResponseConfig<ListMcpToolsByServerQueryResponse>,
  TQueryKey extends QueryKey = ListMcpToolsByServerInfiniteQueryKey
>(
  mcp_server_name: ListMcpToolsByServerPathParams['mcp_server_name'],
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<ListMcpToolsByServerQueryResponse>,
        ResponseErrorConfig<ListMcpToolsByServer422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ??
    listMcpToolsByServerInfiniteQueryKey(mcp_server_name);

  const query = useInfiniteQuery(
    {
      ...(listMcpToolsByServerInfiniteQueryOptions(
        mcp_server_name,
        config
      ) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<
        InfiniteQueryObserverOptions,
        'queryKey'
      >),
    },
    queryClient
  ) as UseInfiniteQueryResult<
    TData,
    ResponseErrorConfig<ListMcpToolsByServer422>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
