/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  ListComposioActionsByAppQueryResponse,
  ListComposioActionsByAppPathParams,
  ListComposioActionsByApp422,
} from '../../types/ListComposioActionsByApp.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  InfiniteQueryObserverOptions,
  UseInfiniteQueryResult,
} from '@tanstack/react-query';
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query';

export const listComposioActionsByAppInfiniteQueryKey = (
  composio_app_name: ListComposioActionsByAppPathParams['composio_app_name']
) =>
  [
    {
      url: '/v1/tools/composio/apps/:composio_app_name/actions',
      params: { composio_app_name: composio_app_name },
    },
  ] as const;

export type ListComposioActionsByAppInfiniteQueryKey = ReturnType<
  typeof listComposioActionsByAppInfiniteQueryKey
>;

/**
 * @description Get a list of all Composio actions for a specific app
 * @summary List Composio Actions By App
 * {@link /v1/tools/composio/apps/:composio_app_name/actions}
 */
export async function listComposioActionsByAppInfinite(
  composio_app_name: ListComposioActionsByAppPathParams['composio_app_name'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    ListComposioActionsByAppQueryResponse,
    ResponseErrorConfig<ListComposioActionsByApp422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/tools/composio/apps/${composio_app_name}/actions`,
    ...requestConfig,
  });
  return res;
}

export function listComposioActionsByAppInfiniteQueryOptions(
  composio_app_name: ListComposioActionsByAppPathParams['composio_app_name'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = listComposioActionsByAppInfiniteQueryKey(composio_app_name);
  return infiniteQueryOptions<
    ResponseConfig<ListComposioActionsByAppQueryResponse>,
    ResponseErrorConfig<ListComposioActionsByApp422>,
    ResponseConfig<ListComposioActionsByAppQueryResponse>,
    typeof queryKey
  >({
    enabled: !!composio_app_name,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listComposioActionsByAppInfinite(composio_app_name, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  });
}

/**
 * @description Get a list of all Composio actions for a specific app
 * @summary List Composio Actions By App
 * {@link /v1/tools/composio/apps/:composio_app_name/actions}
 */
export function useListComposioActionsByAppInfinite<
  TData = InfiniteData<ResponseConfig<ListComposioActionsByAppQueryResponse>>,
  TQueryData = ResponseConfig<ListComposioActionsByAppQueryResponse>,
  TQueryKey extends QueryKey = ListComposioActionsByAppInfiniteQueryKey
>(
  composio_app_name: ListComposioActionsByAppPathParams['composio_app_name'],
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<ListComposioActionsByAppQueryResponse>,
        ResponseErrorConfig<ListComposioActionsByApp422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ??
    listComposioActionsByAppInfiniteQueryKey(composio_app_name);

  const query = useInfiniteQuery(
    {
      ...(listComposioActionsByAppInfiniteQueryOptions(
        composio_app_name,
        config
      ) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<
        InfiniteQueryObserverOptions,
        'queryKey'
      >),
    },
    queryClient
  ) as UseInfiniteQueryResult<
    TData,
    ResponseErrorConfig<ListComposioActionsByApp422>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
