/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios';
import type {
  ListComposioAppsQueryResponse,
  ListComposioAppsHeaderParams,
  ListComposioApps422,
} from '../../types/ListComposioApps.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
  ResponseConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  InfiniteQueryObserverOptions,
  UseInfiniteQueryResult,
} from '@tanstack/react-query';
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query';

export const listComposioAppsInfiniteQueryKey = () =>
  [{ url: '/v1/tools/composio/apps' }] as const;

export type ListComposioAppsInfiniteQueryKey = ReturnType<
  typeof listComposioAppsInfiniteQueryKey
>;

/**
 * @description Get a list of all Composio apps
 * @summary List Composio Apps
 * {@link /v1/tools/composio/apps}
 */
export async function listComposioAppsInfinite(
  headers?: ListComposioAppsHeaderParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    ListComposioAppsQueryResponse,
    ResponseErrorConfig<ListComposioApps422>,
    unknown
  >({
    method: 'GET',
    url: `/v1/tools/composio/apps`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res;
}

export function listComposioAppsInfiniteQueryOptions(
  headers?: ListComposioAppsHeaderParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const queryKey = listComposioAppsInfiniteQueryKey();
  return infiniteQueryOptions<
    ResponseConfig<ListComposioAppsQueryResponse>,
    ResponseErrorConfig<ListComposioApps422>,
    ResponseConfig<ListComposioAppsQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listComposioAppsInfinite(headers, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  });
}

/**
 * @description Get a list of all Composio apps
 * @summary List Composio Apps
 * {@link /v1/tools/composio/apps}
 */
export function useListComposioAppsInfinite<
  TData = InfiniteData<ResponseConfig<ListComposioAppsQueryResponse>>,
  TQueryData = ResponseConfig<ListComposioAppsQueryResponse>,
  TQueryKey extends QueryKey = ListComposioAppsInfiniteQueryKey
>(
  headers?: ListComposioAppsHeaderParams,
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<ListComposioAppsQueryResponse>,
        ResponseErrorConfig<ListComposioApps422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {}
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? listComposioAppsInfiniteQueryKey();

  const query = useInfiniteQuery(
    {
      ...(listComposioAppsInfiniteQueryOptions(
        headers,
        config
      ) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<
        InfiniteQueryObserverOptions,
        'queryKey'
      >),
    },
    queryClient
  ) as UseInfiniteQueryResult<
    TData,
    ResponseErrorConfig<ListComposioApps422>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
